name: Build on Tag

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the latest tag
      id: get_latest_tag
      uses: actions-ecosystem/action-get-latest-tag@v1

    - name: Run tests
      id: run_tests
      run: |
        echo "Run tests"

    - name: Build docker image
      id: docker_image
      run: |
        echo "Build docker image"

    - name: Push the version to acr
      id: push_acr
      run: |
        echo "Push the image to acr"
