name: Deploy on Tag

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract tag name
      id: extract_tag
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        echo "Running tests"

     - name: Build docker image
      run: |
        echo "Building docker image"
    
    - name: Deploy to dev
      run: |
        echo "deploy to dev"
