name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version'
        required: true
        default: 'latest'
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the latest tag
      id: get_latest_tag
      uses: actions-ecosystem/action-get-latest-tag@v1

    - name: Get the version from acr
      id: get_acr
      run: |
        echo "Get the image to acr"

    - name: Deploy application
      id: deploy_app
      run: |
        echo "Deploy application"


